	# This file contains the fastlane.tools configuration
	# You can find the documentation at https://docs.fastlane.tools
	#
	# For a list of all available actions, check out
	#
	#     https://docs.fastlane.tools/actions
	#
	# For a list of all available plugins, check out
	#
	#     https://docs.fastlane.tools/plugins/available-plugins
	#

	# Uncomment the line if you want fastlane to automatically update itself
	# update_fastlane

	default_platform(:ios)

	platform :ios do
	  desc "Description of what the lane does"
	  lane :example do
	      puts("this is my first 🚀 lane")
	   end

	   desc "Pasamos los test"
	   lane :tests do
		scan(scheme: "Project Fastlane")
	    end

	    # Beta Settings
	# Scheme: “DEBUG"
	  lane :beta do

	# Change INFO_PLIST_PATH

	  checkNewVersionStart = get_info_plist_value(path: "./Project\ Fastlane/Info.plist", key: "CFBundleVersion")
	  if checkNewVersionStart == "0"
	  increment_build_number(
	      build_number: "0"
	  )
	  end

	  formerNumber = get_build_number

	  increment_build_number
	  build_number = get_build_number
	  increment_version_number(bump_type: "patch")
	  version = get_version_number

	  formerVersion = "#{version}-b#{formerNumber}"
	  commitVersion = "#{version}-b#{build_number}"

	  set_info_plist_value(path: "./Project\ Fastlane/Info.plist", key: "CFBundleVersion", value: build_number)
	  
	  commit_version_bump(
	      message: "Version #{commitVersion}"
	      )
	  add_git_tag(
	      grouping: "v#{version}",
	      build_number: commitVersion
	      )
	  push_to_git_remote
	  end
		
	end
